using TrifoldDesk.Core;

var root = Path.Combine(Environment.CurrentDirectory, ".test-data", "TrifoldDesk-tests-" + Guid.NewGuid());
Directory.CreateDirectory(root);
int passed = 0;
void Check(bool condition, string name) { if (!condition) throw new Exception("FAIL: " + name); Console.WriteLine("PASS: " + name); passed++; }
try
{
    var store = new ConfigManager(root);
    var first = store.Load<ShortcutConfig>("shortcuts.json");
    Check(first.Value.Items.Count == 0, "first run is empty");
    first.Value.Items.Add(new ShortcutItem { Name = "项目", SourcePath = @"C:\项目\入口.lnk", TargetPath = @"C:\tools\app.exe", Arguments = "--workspace test", WorkingDirectory = @"C:\项目", ScreenIndex = 1 });
    store.Save("shortcuts.json", first.Value);
    var loaded = store.Load<ShortcutConfig>("shortcuts.json").Value;
    Check(loaded.Items[0].Arguments == "--workspace test" && loaded.Items[0].Name == "项目", "shortcut arguments and Unicode roundtrip");
    Check(ShortcutRules.IsDuplicate(loaded.Items, @"c:\项目\入口.lnk", 1), "same screen duplicates are case insensitive");
    Check(!ShortcutRules.IsDuplicate(loaded.Items, @"c:\项目\入口.lnk", 0), "same target allowed on another screen");
    store.Save("shortcuts.json", loaded);
    File.WriteAllText(Path.Combine(root, "shortcuts.json"), "{broken");
    var recovered = store.Load<ShortcutConfig>("shortcuts.json");
    Check(recovered.Value.Items.Count == 1 && recovered.Warning != null, "corrupt primary restores valid backup with warning");
    Check(Directory.GetFiles(root, "shortcuts.json.corrupt-*").Length == 1, "corrupt primary is preserved");
    var other = new ConfigManager(Path.Combine(root, "bad"));
    Directory.CreateDirectory(Path.Combine(root, "bad"));
    File.WriteAllText(Path.Combine(root, "bad", "settings.json"), "null");
    Check(other.Load<AppSettings>("settings.json").Warning != null, "JSON null is treated as corruption");
    Check(RateMath.BytesPerSecond(200, 100, 2) == 50, "network rate uses elapsed time");
    Check(RateMath.BytesPerSecond(10, 100, 2) == 0, "network counter reset is safe");
    Check(RateMath.BytesPerSecond(200, 100, 0) == 0, "zero elapsed time is safe");
    var alpha = new ShortcutItem { Name = "Alpha", Group = "开发", SourcePath = @"C:\tools\alpha.exe", ScreenIndex = 0 };
    var beta = new ShortcutItem { Name = "Beta", Group = "学习", SourcePath = @"C:\docs\beta.txt", ScreenIndex = 1 };
    Check(LibraryRules.Matches(alpha, "ALPHA", "开发"), "search and group filter combine ignoring case");
    Check(!LibraryRules.Matches(alpha, "Alpha", "学习"), "other group is excluded");
    Check(LibraryRules.Matches(beta, "docs", "全部分组"), "search matches source path");
    Check(LibraryRules.SortByName([beta, alpha], false)[0] == alpha, "name ascending order");
    Check(LibraryRules.SortByName([alpha, beta], true)[0] == beta, "name descending order");
    Check(!LibraryRules.CanMove(alpha, [alpha, new ShortcutItem { SourcePath = alpha.SourcePath, ScreenIndex = 1 }], 1), "batch move cannot create duplicate on destination");
    Check(LibraryRules.CanMove(alpha, [alpha, beta], 1), "batch move allowed without duplicate");
    var size = WorkspaceLayout.Expanded(1920, 1040, 144);
    Check(size.Width == (1920 - 24) / 1.5 && size.Height == 1040 / 1.5, "expanded workspace fills area respecting DPI and handle");
    store.Save("groups.json", new ShortcutConfig { Items = [alpha] });
    Check(store.Load<ShortcutConfig>("groups.json").Value.Items[0].Group == "开发", "group persistence roundtrip");
    var defaultWidgets = PluginRules.Defaults(false);
    Check(defaultWidgets.Items.Count(i => i.PluginId == "calendar") == 1 && !defaultWidgets.Items.Any(i => i.PluginId == "cpu"), "new desktop defaults are selective and include calendar");
    var widgets = new WidgetConfig();
    var firstCalendar = PluginRules.Add(widgets, "calendar", 0);
    PluginRules.Add(widgets, "calendar", 2);
    Check(widgets.Items.Count == 2 && widgets.Items[0].InstanceId != widgets.Items[1].InstanceId, "calendar supports distinct instances across panes");
    PluginRules.Add(widgets, "cpu", 2);
    Check(!PluginRules.CanAdd(widgets, "cpu", 2) && !PluginRules.CanAdd(widgets, "cpu", 0), "single instance system metric cannot duplicate across panes");
    Check(PluginRules.CanAdd(new WidgetConfig(), "cpu", 0), "status plugin can be placed on any pane");
    store.Save("widgets.json", widgets);
    Check(store.Load<WidgetConfig>("widgets.json").Value.Items.Count == 3, "widget instances persist separately from shortcuts");
    widgets.Items.Remove(firstCalendar);
    Check(widgets.Items.Count(i => i.PluginId == "calendar") == 1, "removing one calendar preserves another");
    var leapMonth = CalendarMonth.Days(new DateTime(2024, 2, 15));
    Check(leapMonth.Count == 42 && leapMonth[0].Date.DayOfWeek == DayOfWeek.Monday && leapMonth.Count(d => d.InMonth) == 29, "calendar leap February and Monday first grid");
    Check(leapMonth.Zip(leapMonth.Skip(1)).All(p => p.Second.Date == p.First.Date.AddDays(1)), "calendar grid dates continuous across month boundaries");
    Check(!string.IsNullOrWhiteSpace(CalendarMonth.LunarText(new DateTime(2026, 10, 4))), "Chinese lunar label available for supported date");
    Check(PluginRules.Catalog.Any(p => p.Id == "folder" && p.Multiple), "application folders support multiple independent desktop instances");
    var folderWidgets = new WidgetConfig();
    var folderOne = PluginRules.Add(folderWidgets, "folder", 0);
    var folderTwo = PluginRules.Add(folderWidgets, "folder", 1);
    Check(folderOne.InstanceId != folderTwo.InstanceId, "folder identity is independent");
    folderOne.X = 300; folderOne.Y = 70; folderOne.Width = 420; folderOne.Height = 360; folderOne.IsCollapsed = true; folderOne.IsLocked = true;
    var isolatedLayout = PluginRules.Clone(folderWidgets); isolatedLayout.Items[0].X = 1;
    Check(folderWidgets.Items[0].X == 300, "editing layout does not mutate current desktop");
    var bounds = WidgetLayout.Clamp(900, 700, 420, 360, 800, 600);
    Check(bounds.X == 380 && bounds.Y == 240 && bounds.Width == 420, "moving a plugin clamps to visible workspace");
    var tiny = WidgetLayout.Clamp(-10, -20, 500, 500, 180, 120);
    Check(tiny.X == 0 && tiny.Y == 0 && tiny.Width == 180 && tiny.Height == 120, "smaller monitor keeps plugin within work area");
    Check(WidgetLayout.NearestPane(540, 300, 1800) == 1, "crossing component belongs to nearest pane by center");
    var paneBounds = WidgetLayout.ClampToPane(540, 10, 1000, 250, 1, 1800, 900);
    Check(paneBounds.X == 600 && paneBounds.Width == 600 && paneBounds.X + paneBounds.Width <= 1200, "oversized component fits wholly inside its pane");
    var wallBounds = WidgetLayout.ClampToPane(1170, 850, 250, 200, 1, 1800, 900);
    Check(wallBounds.X == 950 && wallBounds.Y == 700, "component touches pane wall instead of crossing it");
    var folders = new FolderConfig { Items = [new FolderData { Id = "a", Items = [alpha] }, new FolderData { Id = "b", Items = [beta] }] };
    var movedFolders = FolderRules.Transfer(folders, "a", "b", alpha.Id, 0, false);
    Check(movedFolders.Items[0].Items.Count == 0 && movedFolders.Items[1].Items[0].Id == alpha.Id && folders.Items[0].Items.Count == 1, "folder move is ordered and isolated until saved");
    var copiedFolders = FolderRules.Transfer(folders, "a", "b", alpha.Id, 0, true);
    var reorder = new FolderConfig { Items=[new FolderData { Id="order", Items=[alpha,beta] }] };
    Check(FolderRules.Transfer(reorder,"order","order",alpha.Id,1,false).Items[0].Items[0].Id==alpha.Id,"dropping before next item does not skip its insertion position");
    Check(FolderRules.Transfer(reorder,"order","order",alpha.Id,2,false).Items[0].Items[1].Id==alpha.Id,"dropping after next item reorders within folder");
    var slotted=FolderRules.Place(reorder,"order","order",alpha.Id,2,false);
    Check(slotted.Items[0].Slots[alpha.Id]==2 && slotted.Items[0].Slots[beta.Id]==1 && !slotted.Items[0].Slots.Values.Contains(0),"first icon moves to third slot leaving first empty without shifting neighbors");
    store.Save("slots.json",slotted);
    Check(FolderRules.Positions(store.Load<FolderConfig>("slots.json").Value.Items[0])[alpha.Id]==2,"empty slots survive reload");
    var slotCopy=FolderRules.Place(folders,"a","b",alpha.Id,3,true);
    Check(slotCopy.Items[0].Items[0].Id==alpha.Id && slotCopy.Items[1].Items.Last().Id!=alpha.Id,"slot copy retains source identity and assigns independent destination entry");
    Check(copiedFolders.Items[0].Items.Count == 1 && copiedFolders.Items[1].Items.Count == 2, "control drag copies without removing source");
    var duplicates = new FolderConfig { Items = [new FolderData { Id = "a", Items = [alpha] }, new FolderData { Id = "b", Items = [alpha] }] };
    Check(FolderRules.Transfer(duplicates, "a", "b", alpha.Id, 0, false).Items[0].Items.Count == 1, "duplicate destination does not lose original membership");
    var emptyDestination = FolderRules.Transfer(folders, "a", "new-folder", alpha.Id, 0, false);
    Check(emptyDestination.Items.Any(f => f.Id == "new-folder" && f.Items.Count == 1), "dragging into a newly created empty folder initializes its content");
    store.Save("free-layout.json", folderWidgets);
    var restoredFolder = store.Load<WidgetConfig>("free-layout.json").Value.Items[0];
    Check(restoredFolder.IsCollapsed && restoredFolder.IsLocked && restoredFolder.X == 300 && restoredFolder.Width == 420, "position size lock and collapse survive restart");
    Check(new[] { "clock", "battery", "gpu" }.All(id => PluginRules.Catalog.Any(p => p.Id == id)), "complete dashboard catalog includes clock battery and GPU");
    var themed = new WidgetConfig(); PluginRules.Add(themed, "cpu", 2, "neon");
    Check(themed.Items[0].Style == "neon" && PluginRules.Normalize(themed).Items[0].Style == "neon", "neon appearance survives validation");
    Check(PluginRules.Catalog.Any(p => p.Id == "system-summary"), "combined system summary is selectable");
    var summaryConfig = new WidgetConfig(); var summary = PluginRules.Add(summaryConfig, "system-summary", 2);
    summary.Modules = ["cpu", "gpu", "bad", "cpu"];
    var summaryClean = PluginRules.Normalize(summaryConfig);
    Check(summaryClean.Items[0].Modules.SequenceEqual(new[] { "cpu", "gpu" }), "summary removes invalid and duplicate modules");
    Check(SummaryRules.Needs(summaryClean, "cpu") && !SummaryRules.Needs(summaryClean, "memory"), "summary sampling follows selected modules");
    PluginRules.Add(summaryClean, "memory", 0);
    Check(SummaryRules.Needs(summaryClean, "memory"), "standalone and summary share sampling requirements");
    store.Save("summary.json", summaryClean);
    Check(store.Load<WidgetConfig>("summary.json").Value.Items[0].Modules.SequenceEqual(new[] { "cpu", "gpu" }), "summary module choices persist");
    Check(PluginRules.Normalize(new WidgetConfig { Items = Enumerable.Range(0, 30).Select(_ => new WidgetInstance { PluginId="folder" }).ToList() }).Items.Count == 30, "normalization preserves migrated layout above add limit");
    ConfigTransactionTests.Run(Check);
    FolderWorkspaceTests.Run(Check);
    ScriptLaunchTests.Run(Check);
    CalendarEventsTests.Run(Check);
    PlacementTests.Run(Check);
    HardwareSensorTests.Run(Check);
    ExtraWidgetTests.Run(Check);
    MonitorLayoutTests.Run(Check);
    PluginProtocolTests.Run(Check);
    ProfilePackageTests.Run(Check);
    LegacyMigrationTests.Run(Check);
    Console.WriteLine($"{passed} checks passed.");
}
finally { Directory.Delete(root, true); }
